ImportFile/ImportFile/Models/ErrorViewModel.cs
using System;

namespace ImportFile.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ImportFile/ImportFile/Models/UsersModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ImportFile.Models
{
    public class UsersModel
    {
        public string FullName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ExternalEmail { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public String DateOfBirth { get; set; }
        public string University { get; set; }
        public string Faculty { get; set; }
        public string Skill { get; set; }
    }
}

ImportFile/ImportFile/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ImportFile.Models;
using Microsoft.AspNetCore.Http;

namespace ImportFile.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult ImportClass()
        {
            return View();
        }



        [HttpPost]
        public IActionResult ImportClass(IFormFile file)
        {
            return View();
        }
    }
}

ImportFile/ImportFile/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ExcelDataReader;
using ImportFile.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ImportFile.Controllers
{
    public class UsersController : Controller
    {
        [HttpGet]
        public IActionResult Index(List<UsersModel> users = null)
        {
            users = users == null ? new List<UsersModel>() : users;
            return View(users);
        }
        [HttpPost]
        [Obsolete]
        public IActionResult Index(IFormFile file, [FromServices] IHostingEnvironment hostingEnvironment)
        {
            string fileName = $"{ hostingEnvironment.WebRootPath}\\files\\{file.FileName}";
            using (FileStream fileStream = System.IO.File.Create(fileName))
            {
                file.CopyTo(fileStream);
                fileStream.Flush();

            }
            var users = this.GetUserList(file.FileName);
            return Index(users);
        }
        private List<UsersModel> GetUserList(string fName)
        {
            List<UsersModel> users = new List<UsersModel>();
            var fileName = $"{Directory.GetCurrentDirectory()}{@"\wwwroot\files"}" + "\\" + fName;
            System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
            using (var stream = System.IO.File.Open(fileName, FileMode.Open, FileAccess.Read))
            {
                using (var reader = ExcelReaderFactory.CreateReader(stream))
                {
                    while (reader.Read())
                    {
                        users.Add(new UsersModel()
                        {

                            FullName = reader.GetValue(0).ToString(),
                            PhoneNumber = reader.GetValue(1).ToString(),
                            Email = reader.GetValue(2).ToString(),
                            FirstName = reader.GetValue(3).ToString(),
                            LastName = reader.GetValue(4).ToString(),
                            ExternalEmail = reader.GetValue(5).ToString(),
                            Account = reader.GetValue(6).ToString(),
                            Password = reader.GetValue(7).ToString(),
                            Gender = reader.GetValue(8).ToString(),
                            DateOfBirth = reader.GetValue(9).ToString(),
                            University = reader.GetValue(10).ToString(),
                            Faculty = reader.GetValue(11).ToString(),
                            Skill = reader.GetValue(12).ToString()
                        });
                    }
                }
            }
            return users;
        }

    }
}

ImportFile/ImportFile/Views/Home/ImportClass.cshtml
@{ ViewData["Title"] = "Import File"; }




<form method="post" asp-action="ImportClass" asp-controller="Home" asp-area="" enctype="multipart/form-data">
    <div class="form-group custom-file">
        <input type="file" class="custom-file-input" id="customFile" name="file">
        <label class="custom-file-label" for="customFile">Choose file</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

ImportFile/ImportFile/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ImportFile/ImportFile/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ImportFile</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ImportFile</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ImportFile - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ImportFile/ImportFile/Views/Users/Index.cshtml
@model IEnumerable<UsersModel>
@{
    Layout = null;
}
<form asp-controller="Users" asp-action="Index" method="post" enctype="multipart/form-data">
    <input type="file" name="file" />
    <hr />
    <button type="submit">Import</button>
</form>

@if (Model.Count() > 0)
{
    <hr />
    <table cellpadding="0" cellspacing="0" border="1">
        <tr>
            <th>FullName</th>
            <th>PhoneNumber</th>
            <th>Email</th>
            <th>FirstName</th>
            <th>LastName</th>
            <th>ExternalEmail</th>
            <th>Account</th>
            <th>Password</th>
            <th>Gender</th>
            <th>DateOfBirth</th>
            <th>University</th>
            <th>Faculty</th>
            <th>Skill</th>
        </tr>
        @foreach (UsersModel users in Model)
        {
    <tr>
        <td>@users.FullName</td>
        <td>@users.PhoneNumber</td>
        <td>@users.Email</td>
        <td>@users.FirstName</td>
        <td>@users.LastName</td>
        <td>@users.ExternalEmail</td>
        <td>@users.Account</td>
        <td>@users.Password</td>
        <td>@users.Gender</td>
        <td>@users.DateOfBirth</td>
        <td>@users.University</td>
        <td>@users.Faculty</td>
        <td>@users.Skill</td>
    </tr>
        }
    </table>
}